name: publish

on:
  push:
    branches: [ foliage ]

jobs:
  generate: 
    name: "Generate site"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: "Generate static HTML"
        uses: estebanlm/foliage-action@main
        with:
          source: '.'
          target: 'generated'